@extends('templates.worker')
@section('content')
<!-- ============ Body content start ============= -->
<div class="main-content">
   <div class="breadcrumb">
      <h1 class="me-2">Termos de uso</h1>
      <ul>
         <li>{{ Auth::user()->name }}</li>
      </ul>
   </div>
   <div class="separator-breadcrumb border-top"></div>
   <section class="elementor-section elementor-top-section elementor-element elementor-element-fba1e10 elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="fba1e10" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;gradient&quot;}">
   <div class="elementor-container elementor-column-gap-default">
      <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-908e4a6" data-id="908e4a6" data-element_type="column">
         <div class="elementor-widget-wrap elementor-element-populated">
            <div class="elementor-element elementor-element-a283e59 elementor-widget elementor-widget-text-editor" data-id="a283e59" data-element_type="widget" data-widget_type="text-editor.default">
               <div class="elementor-widget-container">
                  <p><strong>TERMOS E CONDIÇÕES DE USO</strong></p>
                  <p>Londrina, 14 de novembro de 2023</p>
                  <p>Versão 1.0</p>
                  <p></p>
                  <p>A PRO7 RECRUTAMENTO E SELECAO LTDA, proprietária do software “POINT PRO”, com sede na cidade de Londrina Estado do Paraná, na Av. Juscelino Kubitschek, Vila Ipiranga, CEP 86010-540, inscrita no CNPJ sob o nº 43.444.738/0001-50, vem apresentar o presente Termo de Uso para o acesso e uso do software e sistema &#8211; Controle de Ponto Eletrônico e Controle de Atividades, “SOFTWARE”, tendo o CLIENTE e USUÁRIO concordado com as seguintes definições e condições.</p>
                  <p><strong>DEFINIÇÕES</strong></p>
                  <p>“EMPRESA” ou CLIENTE é a pessoa jurídica que solicitou os serviços da POINT PRO e assinou as Condições Particulares de Uso previstas no presente instrumento e na proposta firmada, a fim de conceder o controle de ponto e controle de atividades aos USUÁRIOS por meio do SOFTWARE.</p>
                  <p>“USUÁRIO” significa a pessoa física ou jurídica que opera o SOFTWARE, seja de maneira administrativa (CONTRATANTE), seja para registrar sua jornada de trabalho (Colaboradores e demais pessoas inseridas pelo CONTRATANTE no sistema) para controle da sua jornada de trabalho e atividades, como tarefas e demais informações de rotina de Departamento Pessoal.</p>
                  <p>“SOFTWARE” Refere-se ao software e sistema &#8220;POINT PRO&#8221; de Controle de Ponto Eletrônico e Controle de Atividades.<br></p>
                  <p><strong>1. CLÁUSULA PRIMEIRA &#8211; DO OBJETO</strong></p>
                  <p>1.1. A PRO7 RECRUTAMENTO E SELEÇÃO LTDA, por intermédio do presente termo, concede ao CLIENTE uma licença revogável, onerosa, não passível de sublicença, não exclusiva e intransferível para uso do SOFTWARE.</p>
                  <p>1.2. Todo o conteúdo incluído no formato desktop, web, e Aplicativo para aparelhos eletrônicos da POINT PRO, tais como textos, gráficos, logotipos, ícones de botão, imagens, clipes de áudio, downloads digitais, compilação de dados e demais itens que compõem o SOFTWARE são de propriedade da POINT PRO.</p>
                  <p><strong>2. CLÁUSULA SEGUNDA &#8211; OBRIGAÇÕES da POINT PRO </strong></p>
                  <p>2.1. a POINT PRO se compromete a manter os serviços contratados com um SLA &#8211; Service Level Agreement de 98% (noventa e oito por cento), garantindo disponibilidade e acessibilidade do SOFTWARE&nbsp;até o encerramento deste Termo de Uso.&nbsp;</p>
                  <p>2.1.1. Entende-se por Service Level Agreement de 98% como sendo que o software deve estar ativo e acessível por pelo menos 98% (noventa e oito por cento) do tempo total de horas em cada mês. Não serão computados os períodos de manutenção/atualização programados, os quais ocorrerão, preferencialmente, fora do horário comercial, bem como causas provocadas exclusivamente pelo próprio CLIENTE ou por seus terceiros contratados.</p>
                  <p>2.1.2. Caso o software apresente disponibilidade por tempo inferior a 98%, a POINT PRO irá ressarcir em iguais períodos sem custo adicional para o CLIENTE, desde que seja comprovada a indisponibilidade do mesmo.</p>
                  <p>2.2. a POINT PRO dará suporte e buscará soluções para eventuais regularizações e falhas sistêmicas não programadas dentro de prazo hábil, em atenção às reivindicações do CLIENTE, para que este execute seu trabalho conforme os seguintes prazos estabelecidos:</p>
                  <p>Para inconsistências/falhas previsíveis ou de baixa complexidade: quando não imediatamente, no máximo, em 72 (setenta e duas) horas;</p>
                  <p>Para inconsistências/falhas inéditas, imprevisíveis ou de alta complexidade: análise caso a caso, devendo o setor de atendimento informar o prazo para resolução em até 24 (vinte e quatro) horas; e</p>
                  <p>Para demandas em que haja prazo específico definido na legislação, tais seguirão a determinação legal.</p>
                  <p>2.3. a POINT PRO se compromete a adotar medidas para garantir que todas as informações fornecidas pelo CLIENTE sejam divulgadas apenas conforme especificado no Termo de Privacidade, bem como nos documentos exarados pela POINT PRO sobre o tema. Esta, no entanto, não pode garantir que, em função do mau uso do USUÁRIO ou CLIENTE, as informações introduzidas por estes não serão desviadas, interceptadas, excluídas, destruídas ou utilizadas por outras pessoas.</p>
                  <p><strong>3. CLÁUSULA TERCEIRA &#8211; OBRIGAÇÕES DO CLIENTE </strong></p>
                  <p>3.1. O CLIENTE não poderá utilizar e nem permitir que o SOFTWARE seja utilizado para outra finalidade que não seja o processamento de suas informações ou de pessoas físicas e jurídicas incluídas no ato do cadastramento, exceto caso este seja empresa de contabilidade que utiliza o SOFTWARE para processar informações de seus clientes, observados os limites estabelecidos neste documento e na legislação em vigor.</p>
                  <p>3.2. Ao CLIENTE não é permitido:</p>
                  <p>I. contornar ou ignorar medida de proteção tecnológica relacionada ao SOFTWARE;</p>
                  <p>II. desmontar, descompilar, descriptografar, piratear, emular, explorar nem fazer engenharia reversa do SOFTWARE ou do CONTEÚDO incluído ou acessível por meio da POINT PRO, ou, de qualquer outro modo, explorar O SOFTWARE, exceto da forma expressamente permitida pela POINT PRO;</p>
                  <p>III. separar os componentes do SOFTWARE para uso em dispositivos diferentes;</p>
                  <p>IV. publicar, copiar, alugar, arrendar, vender, exportar, importar, distribuir ou emprestar o SOFTWARE a menos que a POINT PRO autorize expressamente a fazer isso;</p>
                  <p>V. ativar o acesso ao SOFTWARE ou modificá-lo por aplicativos ou sistemas de terceiros não autorizados;</p>
                  <p>VI. remover qualquer aviso de direito autoral, direito de marca ou outro aviso de direito de propriedade de qualquer parte do SOFTWARE;</p>
                  <p>VII. servir de justificativa para coletar dados indevidamente ou invadir a privacidade de seus usuários</p>
                  <p>3.3. O CLIENTE, tendo em vista a natureza de registro do SOFTWARE, se compromete a abastecer adequadamente e fidedignamente o sistema com as informações referentes à sua, ou de seus funcionários, rotina de atividades laborais, não havendo o que se falar em responsabilização da POINT PRO em caso de abastecimento errôneo ou que não retrate a realidade da jornada de trabalho de seus colaboradores.</p>
                  <p>3.4. O CLIENTE não poderá usar o SOFTWARE de maneira que possa burlá-lo, danificá-lo, inutilizá-lo, sobrecarregá-lo ou que possa prejudicar de qualquer modo o funcionamento do sistema para o próprio ou para terceiros. Além disso, o USUÁRIO deverá se abster de qualquer prática que possa prejudicar ou manchar a imagem da POINT PRO.</p>
                  <p><strong>4. CLÁUSULA QUARTA &#8211; DOS DIREITOS </strong></p>
                  <p>4.1. a POINT PRO se reserva no direito de promover alterações no presente TERMO DE USO a qualquer tempo para fins de atualização e melhoria na prestação dos serviços. Em decorrência disso, o CLIENTE será informado pela POINT PRO sobre as modificações efetuadas pelo próprio portal.</p>
                  <p>4.2. Todas as alterações entrarão em vigor imediatamente após serem postadas no SOFTWARE. A continuação na utilização dos serviços após as alterações nos TERMOS DE USO significa que o CLIENTE aceita estes termos e quaisquer alterações nos mesmos.</p>
                  <p>4.3. a POINT PRO segue as premissas e requisitos descritos pela legislação trabalhista, em especial, pela Portaria no 671/2021 do Ministério do Trabalho, e suas posteriores alterações, contudo, o sistema depende do correto preenchimento de seus campos e prestações de informações aa POINT PRO, as quais é de responsabilidade única e exclusiva do CLIENTE.</p>
                  <p>4.4. A POINT PRO não será responsabilizado por qualquer procedimento realizado no SOFTWARE ou informação prestada por pessoa não autorizada pela POINT PRO, assim como não se responsabiliza por qualquer incompatibilidade com programas de terceiros decorrente de atualização do SOFTWARE.</p>
                  <p>4.5. A POINT PRO não será responsável em promover o cadastro ou registro de informações do CLIENTE perante terceiros, tais como: i) E-SOCIAL, ii) Previdência Social; iii) Ministério do Trabalho, sindicatos e afins; e iv) dentre outros órgãos Federais, Estaduais, Municipais e demais pessoas jurídicas. Tais responsabilidades decorrem das obrigações trabalhistas, previdenciárias e tributárias do empregador, na forma das respectivas leis. Em especial ao E-social, a obrigação do empregador encontra-se prevista no Decreto que o criou (nº 8.373/2014), em seus artigos 2º, §1º, I e §4º, e posteriores alterações. Deste modo, assim como nos demais casos acima, o CLIENTE entende e concorda que tais obrigações não se confundem com o serviço de registro de rotina laboral prestado pela POINT PRO.</p>
                  <p>4.6 Eventuais integrações (nativa, parcial ou manual) e requisitos mínimos de aparelhos para utilização do SOFTWARE deverão ser previamente verificados pelo CLIENTE e informados/esclarecidos pela POINT PRO, sob pena de não haver qualquer responsabilização da POINT PRO e direito de reembolso por uma contratação realizada sem a devida precaução.</p>
                  <p>4.7 As PARTES estão cientes e concordam que eventuais reembolsos serão apurados caso a caso pelo setor competente, não sendo cabíveis, desde já, os seguintes pedidos:</p>
                  <p>Contratação por equívoco, após o direito de arrependimento, e tendo sido prestadas as devidas informações;</p>
                  <p>Após 60 (sessenta) dias ao período requerido; e</p>
                  <p>Casos em que tenha havido a efetiva prestação de serviços sem que a POINT PRO tenha culpa por eventual motivo do pedido;</p>
                  <p><strong>5. CLÁUSULA QUINTA &#8211; DO PAGAMENTO E REAJUSTE </strong></p>
                  <p>5.1. A forma de pagamento se dará no formato pré-pago. Isto é, o CLIENTE deverá efetuar o pagamento no valor correspondente ao plano escolhido para poder usufruir dos serviços da POINT PRO.</p>
                  <p>5.1.1. O CLIENTE está ciente que a identificação do pagamento poderá ocorrer em até dois dias úteis após a data de pagamento pelo mesmo.</p>
                  <p>5.2. A falta de pagamento de quaisquer valores nas respectivas datas de vencimento poderá causar a suspensão do acesso do CLIENTE e USUÁRIOS ao SOFTWARE até que as pendências financeiras tenham sido regularizadas. O acesso ao SOFTWARE somente será restabelecido após a identificação pela POINT PRO do pagamento integral de todos os valores devidos enquanto o mesmo esteve suspenso.</p>
                  <p>5.3. Os preços estabelecidos neste Termo de Uso e Responsabilidade serão reajustados, anualmente, conforme determina a legislação atual, tendo como alternância os índices de inflação IGP-M &#8211; Índice Geral de Preços do Mercado, divulgado pela Fundação Getúlio Vargas e o IPCA &#8211; Índice Nacional de Preços ao Consumidor Amplo, divulgado pelo Instituto Brasileiro de Geografia e Estatística, sendo escolhido para o reajuste o de menor taxa calculada.</p>
                  <p>5.4. Os pagamentos realizados em atraso serão atualizados monetariamente até a data do pagamento pela variação percentual do IGP-M, ocorrida entre a data do vencimento e a liquidação, e terão o acréscimo de juros de 1% (um por cento) ao mês, estes calculados “pro rata dia”, bem como multa de 2% (dois por cento) ao mês pelo atraso no pagamento.</p>
                  <p><strong>6. CLÁUSULA SEXTA &#8211; DA RESCISÃO </strong></p>
                  <p>6.1. Caso o CLIENTE não resolva a pendência financeira no prazo de 30 (trinta) dias contados do vencimento do valor não pago, a POINT PRO se reserva no direito de rescindir o presente termo e notificar o CLIENTE para que este, em um prazo de 60 (sessenta) dias, promova o resgate dos dados gerados durante a vigência do contrato, sob pena destes serem apagados ou anonimizados do servidor sem que haja qualquer imputação de responsabilidade aa POINT PRO por eventuais perdas e danos.</p>
                  <p>6.2. Qualquer das partes poderá rescindir imotivadamente o presente instrumento mediante comunicação prévia, por escrito, de 30 (trinta) dias via e-mail.</p>
                  <p>6.3. Na hipótese de rescisão pelo CLIENTE, o mesmo está ciente que deverá promover o resgate das informações armazenadas pela POINT PRO pelos meios disponibilizados. Caso contrário, não poderá responsabilizar a POINT PRO por eventuais perdas de dados em decorrência de remoção do servidor.</p>
                  <p>6.3.1 Durante este período suas informações serão disponibilizadas para serem extraídas em formato AFD. Essas informações devem ser extraídas pelo CLIENTE, no prazo mencionado acima e conforme instruções fornecidas pela POINT PRO por meio dos canais de atendimento, sob pena da possibilidade de exclusão de tais dados ou anonimização destes, conforme disposto na legislação em vigor.</p>
                  <p>6.3.2 As PARTES têm ciência e concordam que a obrigação de guarda das informações de natureza trabalhista por tempo determinado em lei é do empregador (Controlador &#8211; CLIENTE) e não do Operador (POINT PRO).</p>
                  <p>6.4 O CLIENTE entende que, ao não efetuar o devido pagamento ou descumprir os presentes termos, poderá ter o serviço suspenso e, permanecendo inadimplente por mais de 30 dias, ensejar o fim da relação permitindo que a POINT PRO exclua ou anonimize seus dados, após prazo improrrogável de 60 dias para backup.</p>
                  <p><strong>7. CLÁUSULA SÉTIMA &#8211; DA CONDUTA DO USUÁRIO </strong></p>
                  <p>7.1. O USUÁRIO concorda em não adicionar, subtrair ou modificar o conteúdo, nem tentar acessar qualquer conteúdo que não é destinado para o CLIENTE.</p>
                  <p>7.2. O USUÁRIO também concorda em não transmitir qualquer material que encoraja condutas que possam constituir uma ofensa criminal, dar origem à responsabilidade civil ou violar qualquer lei ou regulamento aplicável.</p>
                  <p>7.3. O CLIENTE e seus autorizados são os únicos e exclusivos responsáveis pela prestação das informações para abastecimento do SOFTWARE e composição do relatório de atividades, a POINT PRO não será responsabilizada por qualquer equívoco ou conteúdo informado pelo USUÁRIO.</p>
                  <p>7.4. O USUÁRIO deverá entrar em contato em caso de qualquer dúvida com relação às disposições constantes deste Termo de Uso ou da Política de Privacidade através dos meios de comunicação disponibilizados (canais de atendimento ou, quando se referir especificamente à questões relacionadas ao tratamento de dados – <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="8efdfbfee1fcfaebcefee1e7e0fafefce1b9a0ede1e3">[email&#160;protected]</a>.</p>
                  <p><strong>8. CLÁUSULA OITAVA &#8211; DA PROTEÇÃO DE DADOS e CONFIDENCIALIDADE</strong></p>
                  <p>8.1. O CLIENTE entende e concorda que, de acordo com as definições estabelecidas na Lei Geral de Proteção de Dados &#8211; LGPD, possui o papel de CONTROLADOR dos dados dos titulares (quando empregador que trata as informações de seus funcionários) e a POINT PRO de OPERADOR dos dados inseridos na plataforma.</p>
                  <p>8.2. O tratamento de dados realizado pela POINT PRO obedece ao disposto na Lei Geral de Proteção de Dados (Lei Federal nº 13.709/2018) e será único e exclusivamente para identificação das partes envolvidas e marcação de todas as atividades relacionadas à rotina de trabalho daqueles que você indicar e inserir no sistema, na forma da Portaria MTP nº 671/2021, e suas posteriores alterações.</p>
                  <p>8.3. a POINT PRO não cria ou insere informações no sistema, salvo se houver solicitação por escrito pelo CLIENTE. Assim, este entende que é o único responsável pelas informações inseridas no software, pelo cadastramento, permissões, senhas e modo de utilização de seus USUÁRIOS.</p>
                  <p>8.4. a POINT PRO não vende os dados inseridos no sistema, nem compartilha com terceiros estranhos ao serviço prestado.</p>
                  <p>8.5. Caso a POINT PRO estabeleça alguma parceria e venha compartilhar os dados com tais parceiros, tal situação será informada previamente ao titular e contará com o consentimento do mesmo para fins de utilização de tais dados.</p>
                  <p>8.6. O CLIENTE está ciente e entende que os dados inseridos no sistema são armazenados nos servidores da Turbo Cloud (sediada no Brasil), o qual possui padrões internacionais de segurança de dados e privacidade, inclusive perante à Lei Geral de Proteção de Dados, conforme previsão do art. 33, IX, da LGPD.</p>
                  <p>8.7. O tratamento de dados realizado pela POINT PRO possui como base legal a existência de relação contratual estabelecida entre as partes (art. 7º, V, LGPD), a partir do momento que o CLIENTE realiza sua anuência em usar o software e se mantém adimplente com as obrigações da relação. Cabe ao CLIENTE buscar as devidas bases legais perante seus respectivos colaboradores e terceiros para coleta de suas informações, sejam elas meramente cadastrais ou relativas a dados sensíveis.</p>
                  <p>8.8. Para usuários que acessam o site, autorizando os cookies, ou se cadastram seus dados para obtenção de informações e materiais, esses concordam que, ao inserirem seus dados pessoais, estão concedendo sua autorização para o tratamento de seus dados, incluindo o recebimento de comunicações e e-mails da POINT PRO.</p>
                  <p>8.9. a POINT PRO lhe informará, dentro do prazo legal estabelecido para tal situação, sob eventual ocorrência de incidente de segurança no tratamento de seus dados, bem como atuará prioritariamente para remediar a situação ou contribuir para a resolução do evento.</p>
                  <p>8.10. As informações tratadas na presente relação, ressalvadas aquelas já consideradas públicas ou autorizadas formalmente pela parte emissora, terão natureza confidencial e não poderão ser compartilhadas com outras empresas estranhas à prestação de serviço.</p>
                  <p>8.10.1. As PARTES assumem o compromisso de cientificar, inclusive por instrumento contratual, seus respectivos colaboradores e prestadores de serviços sobre o caráter sigiloso das informações tratadas, divulgando-as somente aos empregados e terceiros que necessitem ter acesso a elas para os propósitos destes termos.</p>
                  <p>8.11. Em casos de Suporte Técnico solicitado pelo CLIENTE, a Point Pro poderá necessitar realizar o acesso remoto aos computadores do CLIENTE, este acesso desde já fica autorizado, sob supervisão e apenas desta maneira. O CLIENTE autoriza o acesso remoto aos seus computadores, de forma supervisionada para fins de suporte técnico.<br></p>
                  <p><strong>9. CLÁUSULA NONA &#8211; SOBRE A DEMONSTRAÇÃO DE INICIALIZAÇÃO </strong></p>
                  <p>9.1. Para os clientes que contratarem o serviço de DEMONSTRAÇÃO DE INICIALIZAÇÃO, este consiste em uma prestação de serviço de atendimento personalizado, por tempo limitado, para auxiliar você na utilização da ferramenta POINT PRO, bem como prestar consultoria por canais exclusivos para esclarecimentos, gestão da ferramenta e dos registros de ponto e acompanhamento por meio de reuniões periódicas e treinamentos online.</p>
                  <p>9.2. A contratação do serviço de DEMONSTRAÇÃO DE INICIALIZAÇÃO pode ser feita a qualquer tempo, por quantas vezes O CLIENTE entender necessário e mediante sua solicitação.</p>
                  <p>9.3. O serviço possui prazo determinado, o qual será previsto na Proposta comercial e começará a contar a partir do momento do pagamento, podendo haver tolerância de 3 (três) dias para início das atividades.</p>
                  <p>9.4. a POINT PRO poderá, por liberalidade, prorrogar o tempo de prestação de serviço.</p>
                  <p>9.5. a POINT PRO se compromete a dar imediato início a DEMONSTRAÇÃO DE INICIALIZAÇÃO e não se responsabiliza pela sua demora e indisponibilidade para começar o citado serviço. Nesses casos, o tempo da prestação do serviço terá início a partir do pagamento, respeitando a tolerância informada acima, podendo o CLIENTE usufruir do tempo restante a partir de sua disponibilidade.</p>
                  <p>9.6. O não aproveitamento do tempo total, por indisponibilidade ou demora exclusiva do CLIENTE, será de sua responsabilidade, não cabendo qualquer ressarcimento do período não aproveitado ou remarcação do citado serviço.</p>
                  <p><strong>10. CLÁUSULA DÉCIMA &#8211; DAS DISPOSIÇÕES GERAIS </strong></p>
                  <p>10.1. Da Anticorrupção. Pelo presente instrumento contratual, a POINT PRO e o CLIENTE se comprometem a observar as normais legais vigentes no país, incluindo, mas não se limitando, à Lei Anticorrupção (Lei nº 12.846/2013) e à Lei contra a Lavagem de Dinheiro (Lei nº 12.846/2013), bem como se obriga a agir em consonância às políticas internas do CLIENTE.</p>
                  <p>10.2. Da ausência de vínculo trabalhista. Não haverá qualquer responsabilidade subsidiária ou solidária da POINT PRO sobre eventuais encargos trabalhistas, tributários, previdenciários ou decorrentes de qualquer compromisso assumido com terceiros pelo CLIENTE.</p>
                  <p>10.3. Da concordância. Acerca da Intrajornada e demais informações referentes à rotina laboral, o USUÁRIO concorda que, conforme estabelecido pelo art. 71 da Consolidação das Leis Trabalhistas (Decreto-Lei nº 5.452/43), e suas alterações, bem como pela natureza de registro de rotina laboral da POINT PRO, o registro de tal intervalo (seu início e fim) é de única e exclusiva responsabilidade do CLIENTE e de seus empregados. Deste modo, não há o que se falar em responsabilidade da POINT PRO em caso de não marcação ou correção da intrajornada pelo USUÁRIO e de inserção de informações realizadas no registro do colaborador.</p>
                  <p><strong>11. CLÁUSULA DÉCIMA PRIMEIRA &#8211; DO FORO </strong></p>
                  <p>11.1. As Partes elegem o Foro da Comarca de Londrina &#8211; PR para a solução de quaisquer litígios decorrentes deste Termo de Uso.</p>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- end of main-content -->
@endsection